// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: product-service/product.proto

package productpb

import (
	common "github.com/krismandev/protobuf-spec/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Product struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	OwnerType     string                 `protobuf:"bytes,4,opt,name=owner_type,json=ownerType,proto3" json:"owner_type,omitempty"`
	OwnerId       string                 `protobuf:"bytes,5,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	FeaturedImage string                 `protobuf:"bytes,6,opt,name=featured_image,json=featuredImage,proto3" json:"featured_image,omitempty"`
	HasVariants   string                 `protobuf:"bytes,7,opt,name=has_variants,json=hasVariants,proto3" json:"has_variants,omitempty"`
	Price         float64                `protobuf:"fixed64,8,opt,name=price,proto3" json:"price,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_product_service_product_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_product_service_product_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_product_service_product_proto_rawDescGZIP(), []int{0}
}

func (x *Product) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Product) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Product) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Product) GetOwnerType() string {
	if x != nil {
		return x.OwnerType
	}
	return ""
}

func (x *Product) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *Product) GetFeaturedImage() string {
	if x != nil {
		return x.FeaturedImage
	}
	return ""
}

func (x *Product) GetHasVariants() string {
	if x != nil {
		return x.HasVariants
	}
	return ""
}

func (x *Product) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Product) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Product) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type GetProductsRequest struct {
	state             protoimpl.MessageState        `protogen:"open.v1"`
	GlobalListRequest *common.GlobalListDataRequest `protobuf:"bytes,1,opt,name=globalListRequest,proto3" json:"globalListRequest,omitempty"`
	Name              string                        `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	OwnerId           string                        `protobuf:"bytes,5,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetProductsRequest) Reset() {
	*x = GetProductsRequest{}
	mi := &file_product_service_product_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductsRequest) ProtoMessage() {}

func (x *GetProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_service_product_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductsRequest.ProtoReflect.Descriptor instead.
func (*GetProductsRequest) Descriptor() ([]byte, []int) {
	return file_product_service_product_proto_rawDescGZIP(), []int{1}
}

func (x *GetProductsRequest) GetGlobalListRequest() *common.GlobalListDataRequest {
	if x != nil {
		return x.GlobalListRequest
	}
	return nil
}

func (x *GetProductsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetProductsRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

type GetProductsResponse struct {
	state              protoimpl.MessageState     `protogen:"open.v1"`
	GlobalListResponse *common.GlobalListResponse `protobuf:"bytes,1,opt,name=globalListResponse,proto3" json:"globalListResponse,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetProductsResponse) Reset() {
	*x = GetProductsResponse{}
	mi := &file_product_service_product_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductsResponse) ProtoMessage() {}

func (x *GetProductsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_service_product_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductsResponse.ProtoReflect.Descriptor instead.
func (*GetProductsResponse) Descriptor() ([]byte, []int) {
	return file_product_service_product_proto_rawDescGZIP(), []int{2}
}

func (x *GetProductsResponse) GetGlobalListResponse() *common.GlobalListResponse {
	if x != nil {
		return x.GlobalListResponse
	}
	return nil
}

var File_product_service_product_proto protoreflect.FileDescriptor

const file_product_service_product_proto_rawDesc = "" +
	"\n" +
	"\x1dproduct-service/product.proto\x12\aproduct\x1a\x12common/types.proto\"\xa7\x02\n" +
	"\aProduct\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"owner_type\x18\x04 \x01(\tR\townerType\x12\x19\n" +
	"\bowner_id\x18\x05 \x01(\tR\aownerId\x12%\n" +
	"\x0efeatured_image\x18\x06 \x01(\tR\rfeaturedImage\x12!\n" +
	"\fhas_variants\x18\a \x01(\tR\vhasVariants\x12\x14\n" +
	"\x05price\x18\b \x01(\x01R\x05price\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\tR\tupdatedAt\"\x90\x01\n" +
	"\x12GetProductsRequest\x12K\n" +
	"\x11globalListRequest\x18\x01 \x01(\v2\x1d.common.GlobalListDataRequestR\x11globalListRequest\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x19\n" +
	"\bowner_id\x18\x05 \x01(\tR\aownerId\"a\n" +
	"\x13GetProductsResponse\x12J\n" +
	"\x12globalListResponse\x18\x01 \x01(\v2\x1a.common.GlobalListResponseR\x12globalListResponse2Z\n" +
	"\x0eProductService\x12H\n" +
	"\vGetProducts\x12\x1b.product.GetProductsRequest\x1a\x1c.product.GetProductsResponseB?Z=github.com/krismandev/protobuf-spec/product-service;productpbb\x06proto3"

var (
	file_product_service_product_proto_rawDescOnce sync.Once
	file_product_service_product_proto_rawDescData []byte
)

func file_product_service_product_proto_rawDescGZIP() []byte {
	file_product_service_product_proto_rawDescOnce.Do(func() {
		file_product_service_product_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_product_service_product_proto_rawDesc), len(file_product_service_product_proto_rawDesc)))
	})
	return file_product_service_product_proto_rawDescData
}

var file_product_service_product_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_product_service_product_proto_goTypes = []any{
	(*Product)(nil),                      // 0: product.Product
	(*GetProductsRequest)(nil),           // 1: product.GetProductsRequest
	(*GetProductsResponse)(nil),          // 2: product.GetProductsResponse
	(*common.GlobalListDataRequest)(nil), // 3: common.GlobalListDataRequest
	(*common.GlobalListResponse)(nil),    // 4: common.GlobalListResponse
}
var file_product_service_product_proto_depIdxs = []int32{
	3, // 0: product.GetProductsRequest.globalListRequest:type_name -> common.GlobalListDataRequest
	4, // 1: product.GetProductsResponse.globalListResponse:type_name -> common.GlobalListResponse
	1, // 2: product.ProductService.GetProducts:input_type -> product.GetProductsRequest
	2, // 3: product.ProductService.GetProducts:output_type -> product.GetProductsResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_product_service_product_proto_init() }
func file_product_service_product_proto_init() {
	if File_product_service_product_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_product_service_product_proto_rawDesc), len(file_product_service_product_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_product_service_product_proto_goTypes,
		DependencyIndexes: file_product_service_product_proto_depIdxs,
		MessageInfos:      file_product_service_product_proto_msgTypes,
	}.Build()
	File_product_service_product_proto = out.File
	file_product_service_product_proto_goTypes = nil
	file_product_service_product_proto_depIdxs = nil
}
