// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: common/types.proto

package commonpb

import (
	any1 "github.com/golang/protobuf/ptypes/any"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Struct umum yang bisa dipakai di banyak service
type GlobalListDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	OrderDir      string                 `protobuf:"bytes,3,opt,name=orderDir,proto3" json:"orderDir,omitempty"`
	OrderBy       string                 `protobuf:"bytes,4,opt,name=orderBy,proto3" json:"orderBy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GlobalListDataRequest) Reset() {
	*x = GlobalListDataRequest{}
	mi := &file_common_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GlobalListDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobalListDataRequest) ProtoMessage() {}

func (x *GlobalListDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlobalListDataRequest.ProtoReflect.Descriptor instead.
func (*GlobalListDataRequest) Descriptor() ([]byte, []int) {
	return file_common_types_proto_rawDescGZIP(), []int{0}
}

func (x *GlobalListDataRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GlobalListDataRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GlobalListDataRequest) GetOrderDir() string {
	if x != nil {
		return x.OrderDir
	}
	return ""
}

func (x *GlobalListDataRequest) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

type GlobalListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	OrderDir      string                 `protobuf:"bytes,4,opt,name=orderDir,proto3" json:"orderDir,omitempty"`
	OrderBy       string                 `protobuf:"bytes,5,opt,name=orderBy,proto3" json:"orderBy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GlobalListResponse) Reset() {
	*x = GlobalListResponse{}
	mi := &file_common_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GlobalListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobalListResponse) ProtoMessage() {}

func (x *GlobalListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlobalListResponse.ProtoReflect.Descriptor instead.
func (*GlobalListResponse) Descriptor() ([]byte, []int) {
	return file_common_types_proto_rawDescGZIP(), []int{1}
}

func (x *GlobalListResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GlobalListResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GlobalListResponse) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GlobalListResponse) GetOrderDir() string {
	if x != nil {
		return x.OrderDir
	}
	return ""
}

func (x *GlobalListResponse) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

type GlobalSingleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Data          *any1.Any              `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GlobalSingleResponse) Reset() {
	*x = GlobalSingleResponse{}
	mi := &file_common_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GlobalSingleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobalSingleResponse) ProtoMessage() {}

func (x *GlobalSingleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlobalSingleResponse.ProtoReflect.Descriptor instead.
func (*GlobalSingleResponse) Descriptor() ([]byte, []int) {
	return file_common_types_proto_rawDescGZIP(), []int{2}
}

func (x *GlobalSingleResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GlobalSingleResponse) GetData() *any1.Any {
	if x != nil {
		return x.Data
	}
	return nil
}

type ResponseMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	TotalData     int32                  `protobuf:"varint,3,opt,name=totalData,proto3" json:"totalData,omitempty"`
	TotalPage     int32                  `protobuf:"varint,4,opt,name=totalPage,proto3" json:"totalPage,omitempty"`
	OrderDir      string                 `protobuf:"bytes,5,opt,name=orderDir,proto3" json:"orderDir,omitempty"`
	OrderBy       string                 `protobuf:"bytes,6,opt,name=orderBy,proto3" json:"orderBy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseMetadata) Reset() {
	*x = ResponseMetadata{}
	mi := &file_common_types_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseMetadata) ProtoMessage() {}

func (x *ResponseMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_common_types_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseMetadata.ProtoReflect.Descriptor instead.
func (*ResponseMetadata) Descriptor() ([]byte, []int) {
	return file_common_types_proto_rawDescGZIP(), []int{3}
}

func (x *ResponseMetadata) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ResponseMetadata) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ResponseMetadata) GetTotalData() int32 {
	if x != nil {
		return x.TotalData
	}
	return 0
}

func (x *ResponseMetadata) GetTotalPage() int32 {
	if x != nil {
		return x.TotalPage
	}
	return 0
}

func (x *ResponseMetadata) GetOrderDir() string {
	if x != nil {
		return x.OrderDir
	}
	return ""
}

func (x *ResponseMetadata) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

var File_common_types_proto protoreflect.FileDescriptor

const file_common_types_proto_rawDesc = "" +
	"\n" +
	"\x12common/types.proto\x12\x06common\x1a\x19google/protobuf/any.proto\"w\n" +
	"\x15GlobalListDataRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x1a\n" +
	"\borderDir\x18\x03 \x01(\tR\borderDir\x12\x18\n" +
	"\aorderBy\x18\x04 \x01(\tR\aorderBy\"\x8e\x01\n" +
	"\x12GlobalListResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x1a\n" +
	"\borderDir\x18\x04 \x01(\tR\borderDir\x12\x18\n" +
	"\aorderBy\x18\x05 \x01(\tR\aorderBy\"Z\n" +
	"\x14GlobalSingleResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12(\n" +
	"\x04data\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\x04data\"\xae\x01\n" +
	"\x10ResponseMetadata\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x1c\n" +
	"\ttotalData\x18\x03 \x01(\x05R\ttotalData\x12\x1c\n" +
	"\ttotalPage\x18\x04 \x01(\x05R\ttotalPage\x12\x1a\n" +
	"\borderDir\x18\x05 \x01(\tR\borderDir\x12\x18\n" +
	"\aorderBy\x18\x06 \x01(\tR\aorderByB5Z3github.com/krismandev/protobuf-spec/common;commonpbb\x06proto3"

var (
	file_common_types_proto_rawDescOnce sync.Once
	file_common_types_proto_rawDescData []byte
)

func file_common_types_proto_rawDescGZIP() []byte {
	file_common_types_proto_rawDescOnce.Do(func() {
		file_common_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_types_proto_rawDesc), len(file_common_types_proto_rawDesc)))
	})
	return file_common_types_proto_rawDescData
}

var file_common_types_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_common_types_proto_goTypes = []any{
	(*GlobalListDataRequest)(nil), // 0: common.GlobalListDataRequest
	(*GlobalListResponse)(nil),    // 1: common.GlobalListResponse
	(*GlobalSingleResponse)(nil),  // 2: common.GlobalSingleResponse
	(*ResponseMetadata)(nil),      // 3: common.ResponseMetadata
	(*any1.Any)(nil),              // 4: google.protobuf.Any
}
var file_common_types_proto_depIdxs = []int32{
	4, // 0: common.GlobalSingleResponse.data:type_name -> google.protobuf.Any
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_common_types_proto_init() }
func file_common_types_proto_init() {
	if File_common_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_types_proto_rawDesc), len(file_common_types_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_types_proto_goTypes,
		DependencyIndexes: file_common_types_proto_depIdxs,
		MessageInfos:      file_common_types_proto_msgTypes,
	}.Build()
	File_common_types_proto = out.File
	file_common_types_proto_goTypes = nil
	file_common_types_proto_depIdxs = nil
}
