// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: common/types.proto

package commonpb

import (
	any1 "github.com/golang/protobuf/ptypes/any"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Struct umum yang bisa dipakai di banyak service
type GlobalListDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	OrderDir      string                 `protobuf:"bytes,3,opt,name=orderDir,proto3" json:"orderDir,omitempty"`
	OrderBy       string                 `protobuf:"bytes,4,opt,name=orderBy,proto3" json:"orderBy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GlobalListDataRequest) Reset() {
	*x = GlobalListDataRequest{}
	mi := &file_common_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GlobalListDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobalListDataRequest) ProtoMessage() {}

func (x *GlobalListDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlobalListDataRequest.ProtoReflect.Descriptor instead.
func (*GlobalListDataRequest) Descriptor() ([]byte, []int) {
	return file_common_types_proto_rawDescGZIP(), []int{0}
}

func (x *GlobalListDataRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GlobalListDataRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GlobalListDataRequest) GetOrderDir() string {
	if x != nil {
		return x.OrderDir
	}
	return ""
}

func (x *GlobalListDataRequest) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

type GlobalListResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Status        string                  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	StatusCode    string                  `protobuf:"bytes,2,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	Message       string                  `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Data          *GlobalListDataResponse `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GlobalListResponse) Reset() {
	*x = GlobalListResponse{}
	mi := &file_common_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GlobalListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobalListResponse) ProtoMessage() {}

func (x *GlobalListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlobalListResponse.ProtoReflect.Descriptor instead.
func (*GlobalListResponse) Descriptor() ([]byte, []int) {
	return file_common_types_proto_rawDescGZIP(), []int{1}
}

func (x *GlobalListResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GlobalListResponse) GetStatusCode() string {
	if x != nil {
		return x.StatusCode
	}
	return ""
}

func (x *GlobalListResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GlobalListResponse) GetData() *GlobalListDataResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

type GlobalSingleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	StatusCode    string                 `protobuf:"bytes,2,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Data          *any1.Any              `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GlobalSingleResponse) Reset() {
	*x = GlobalSingleResponse{}
	mi := &file_common_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GlobalSingleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobalSingleResponse) ProtoMessage() {}

func (x *GlobalSingleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlobalSingleResponse.ProtoReflect.Descriptor instead.
func (*GlobalSingleResponse) Descriptor() ([]byte, []int) {
	return file_common_types_proto_rawDescGZIP(), []int{2}
}

func (x *GlobalSingleResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GlobalSingleResponse) GetStatusCode() string {
	if x != nil {
		return x.StatusCode
	}
	return ""
}

func (x *GlobalSingleResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GlobalSingleResponse) GetData() *any1.Any {
	if x != nil {
		return x.Data
	}
	return nil
}

type GlobalListDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	OrderDir      string                 `protobuf:"bytes,3,opt,name=orderDir,proto3" json:"orderDir,omitempty"`
	OrderBy       string                 `protobuf:"bytes,4,opt,name=orderBy,proto3" json:"orderBy,omitempty"`
	Data          []*any1.Any            `protobuf:"bytes,5,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GlobalListDataResponse) Reset() {
	*x = GlobalListDataResponse{}
	mi := &file_common_types_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GlobalListDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobalListDataResponse) ProtoMessage() {}

func (x *GlobalListDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_types_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlobalListDataResponse.ProtoReflect.Descriptor instead.
func (*GlobalListDataResponse) Descriptor() ([]byte, []int) {
	return file_common_types_proto_rawDescGZIP(), []int{3}
}

func (x *GlobalListDataResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GlobalListDataResponse) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GlobalListDataResponse) GetOrderDir() string {
	if x != nil {
		return x.OrderDir
	}
	return ""
}

func (x *GlobalListDataResponse) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

func (x *GlobalListDataResponse) GetData() []*any1.Any {
	if x != nil {
		return x.Data
	}
	return nil
}

type ResponseMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	OrderDir      string                 `protobuf:"bytes,3,opt,name=orderDir,proto3" json:"orderDir,omitempty"`
	OrderBy       string                 `protobuf:"bytes,4,opt,name=orderBy,proto3" json:"orderBy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseMetadata) Reset() {
	*x = ResponseMetadata{}
	mi := &file_common_types_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseMetadata) ProtoMessage() {}

func (x *ResponseMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_common_types_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseMetadata.ProtoReflect.Descriptor instead.
func (*ResponseMetadata) Descriptor() ([]byte, []int) {
	return file_common_types_proto_rawDescGZIP(), []int{4}
}

func (x *ResponseMetadata) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ResponseMetadata) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ResponseMetadata) GetOrderDir() string {
	if x != nil {
		return x.OrderDir
	}
	return ""
}

func (x *ResponseMetadata) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

var File_common_types_proto protoreflect.FileDescriptor

const file_common_types_proto_rawDesc = "" +
	"\n" +
	"\x12common/types.proto\x12\x06common\x1a\x19google/protobuf/any.proto\"w\n" +
	"\x15GlobalListDataRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x1a\n" +
	"\borderDir\x18\x03 \x01(\tR\borderDir\x12\x18\n" +
	"\aorderBy\x18\x04 \x01(\tR\aorderBy\"\x9a\x01\n" +
	"\x12GlobalListResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1e\n" +
	"\n" +
	"statusCode\x18\x02 \x01(\tR\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x122\n" +
	"\x04data\x18\x04 \x01(\v2\x1e.common.GlobalListDataResponseR\x04data\"\x92\x01\n" +
	"\x14GlobalSingleResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1e\n" +
	"\n" +
	"statusCode\x18\x02 \x01(\tR\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12(\n" +
	"\x04data\x18\x04 \x01(\v2\x14.google.protobuf.AnyR\x04data\"\xa2\x01\n" +
	"\x16GlobalListDataResponse\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x1a\n" +
	"\borderDir\x18\x03 \x01(\tR\borderDir\x12\x18\n" +
	"\aorderBy\x18\x04 \x01(\tR\aorderBy\x12(\n" +
	"\x04data\x18\x05 \x03(\v2\x14.google.protobuf.AnyR\x04data\"r\n" +
	"\x10ResponseMetadata\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x1a\n" +
	"\borderDir\x18\x03 \x01(\tR\borderDir\x12\x18\n" +
	"\aorderBy\x18\x04 \x01(\tR\aorderByB5Z3github.com/krismandev/protobuf-spec/common;commonpbb\x06proto3"

var (
	file_common_types_proto_rawDescOnce sync.Once
	file_common_types_proto_rawDescData []byte
)

func file_common_types_proto_rawDescGZIP() []byte {
	file_common_types_proto_rawDescOnce.Do(func() {
		file_common_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_types_proto_rawDesc), len(file_common_types_proto_rawDesc)))
	})
	return file_common_types_proto_rawDescData
}

var file_common_types_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_common_types_proto_goTypes = []any{
	(*GlobalListDataRequest)(nil),  // 0: common.GlobalListDataRequest
	(*GlobalListResponse)(nil),     // 1: common.GlobalListResponse
	(*GlobalSingleResponse)(nil),   // 2: common.GlobalSingleResponse
	(*GlobalListDataResponse)(nil), // 3: common.GlobalListDataResponse
	(*ResponseMetadata)(nil),       // 4: common.ResponseMetadata
	(*any1.Any)(nil),               // 5: google.protobuf.Any
}
var file_common_types_proto_depIdxs = []int32{
	3, // 0: common.GlobalListResponse.data:type_name -> common.GlobalListDataResponse
	5, // 1: common.GlobalSingleResponse.data:type_name -> google.protobuf.Any
	5, // 2: common.GlobalListDataResponse.data:type_name -> google.protobuf.Any
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_common_types_proto_init() }
func file_common_types_proto_init() {
	if File_common_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_types_proto_rawDesc), len(file_common_types_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_types_proto_goTypes,
		DependencyIndexes: file_common_types_proto_depIdxs,
		MessageInfos:      file_common_types_proto_msgTypes,
	}.Build()
	File_common_types_proto = out.File
	file_common_types_proto_goTypes = nil
	file_common_types_proto_depIdxs = nil
}
